# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  pull_request:
    types:
      - closed
    branches:
      - 'dev'
      - 'main'

jobs:
  if_merged:
    name: Push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: check the variable
        run: |
          echo "github.ref_name $ref_name"
        env:
          ref_name: ${{github.ref_name}}

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref_name}}

      - name: Make application.yml
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application.yml 
          echo "${{ secrets.PROPERTIES_DEV }}" > ./src/main/resources/application.yml
        shell: bash
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image -- main
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name == 'main' }}
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-app-main
      
      - name: Build and push Docker image -- dev
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name == 'dev' }}
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-app

      - name: executing remote ssh commands using ssh key -- main
        uses: appleboy/ssh-action@v1.0.0
        if: ${{ github.ref_name == 'main' }}
        with:
          host: ${{ secrets.MAIN_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sh ../deployback.sh

      - name: executing remote ssh commands using ssh key -- dev
        uses: appleboy/ssh-action@v1.0.0
        if: ${{ github.ref_name == 'dev' }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sh ../deployback.sh
